### ISSUE TITLE
Broken in Firefox 36

### ISSUE THREAD

**Issue by rononline** [zaidka/cliget#12]
I noticed that this not worked anymore in Firefox 36, so i downgraded to 35, and it's working again. 

Am I the only one? Anybody else noticed this?

**Comment by kptkill** [comment]
also not working for me.

**Comment by zaidka** [comment]
This is fixed and an update is submitted to Mozilla and will be published in a couple of days. Alternatively, you could the latest release from here: https://github.com/zaidka/cliget/releases. Thanks for reporting this.

**Comment by AntiSol** [comment]
Hi, I'm using firefox 26.0.4 on ubuntu 12.04 and I don't see the cliget menu.
I've tried removing it and installing version 1.2.2 as linked above, but this makes no difference. Any ideas?

**Comment by AntiSol** [comment]
nevermind, I restarted firefox and now I see it. duh.
