### ISSUE TITLE
Include axel and youtube-dl suport

### ISSUE THREAD

**Issue by pekman1** [zaidka/cliget#15]
hello to all who contribute to this project. I have a deep admiration for all.

I look cliget and see something perfect. However there are two functions that I would like to see.

Support for youtube-dl and axel.

youtube-dl is a fantastic client ncurse supporting nearly 100 sites of media.

axel simply boost the speed of downloads.

Well, I hope to see it one day implemented in cliget.

**Comment by zaidka** [comment]
Thanks pekman, and sorry for the delay. I personally use youtube-dl myself and I just realized that it supports sending custom request headers, which means support for it can be implemented in cliget. Axel also seems to support request headers. I hope I'll be able to implement them both but not sure when. Patches are welcome. Will leave this issue open for now. Thanks!

**Comment by pekman1** [comment]
Ok man, thanks for feedback
