### ISSUE TITLE
Download Box intgration not seen in latest Firefox Nightly 64-bits for Windows.

### ISSUE THREAD

**Issue by charlesmilette** [zaidka/cliget#25]
In the latest Firefox Nightly 64-bits on Windows, I do not see the download box integration, but I can see the context menu entry (and it works):
![sans titre](https://cloud.githubusercontent.com/assets/6440374/11901228/6be4f136-a578-11e5-9411-c6a0fb6d1061.png)

![sans titre2](https://cloud.githubusercontent.com/assets/6440374/11901266/9b818b5c-a578-11e5-9ffd-4a6600adce8f.png)

**Comment by charlesmilette** [comment]
Fixed in latest Nightly...

**Comment by zaidka** [comment]
Great. Thanks for the update :)
