### ISSUE TITLE
Please add axel too

### ISSUE THREAD

**Issue by Rergis** [zaidka/cliget#29]
it's great to have curl, wget, youtube-dl or aria2, personally i'm using axel and would be fantastic to have the combo cliget+axel. 

(maybe a template for linux like):
axel  [URL] --output=[URL] -o $HOME/Downloads

(Sorry for my bad english).

**Comment by Rergis** [comment]
closing.....project seems dormant

**Comment by zaidka** [comment]
The project hasn't been active for a while because I was busy with another project and because it may need a rewrite due to the new under the hood changes in Firefox (e10s and Web Extensions) and I seem to keep putting that off!
