### ISSUE TITLE
Get rid of using CLI for passing arguments to apps

### ISSUE THREAD

**Issue by KOLANICH** [zaidka/cliget#67]
For example, aria2 supports JSON RPC.

**Comment by zaidka** [comment]
Out of scope. Sounds like you'd be better off using a download manager.

**Comment by weberjn** [comment]
see issue [issue 49](https://github.com/zaidka/cliget/issues/49)

and [curlwebmanager](https://github.com/weberjn/curlwebmanager) that has a remote api.
